# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Freelancer\'s Diary' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Freelancer's Diary

end
